require('core.plugin_config.nord-vim')
-- require('core.plugin_config.veil')
require('core.plugin_config.vim-surround')
require('core.plugin_config.vim-commentary')
require('core.plugin_config.vim-airline')
require('core.plugin_config.vim-css-color')
require('core.plugin_config.vim-devicons')
require('core.plugin_config.vim-closer')
require('core.plugin_config.auto-pairs')
require('core.plugin_config.vim-wintabs-powerline')
require('core.plugin_config.telescope')
